"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Activity, ArrowRight, BookOpen, BrainCircuit, ChevronRight, Clock3, Flame, Languages, Library, Search, Sparkles, Trophy } from "lucide-react";

export type DashboardStats = { words_learned?: number; lessons_completed?: number; points?: number; streak_days?: number } | null;
export type DashboardActivity = { action: string; details?: string; score?: string | number; timestamp?: string };

const card = "rounded-xl border border-stone-200 bg-white shadow-[0_1px_2px_rgba(69,45,27,.04)] dark:border-white/10 dark:bg-[var(--bg-card)]";

export function WelcomeBanner({ user, streak }: { user: any; streak: number }) {
  return <section className="relative overflow-hidden rounded-2xl bg-orange-600 px-6 py-6 text-white sm:px-7 sm:py-7">
    <div className="absolute -right-10 -top-16 size-48 rounded-full bg-orange-400/30" />
    <div className="relative flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
      <div><h1 className="text-xl font-bold tracking-tight sm:text-2xl">Namaste, {user?.username} — Welcome back!</h1><p className="mt-1 text-sm text-orange-100">Continue your scholarly journey today. Your analytical training is paying off.</p><div className="mt-4 border-l-2 border-orange-200/70 pl-3"><p className="font-devanagari text-sm font-bold">उद्योगेन हि सिद्ध्यन्ति कार्याणि न मनोरथैः</p><p className="mt-0.5 text-xs text-orange-100/80">“Actions are accomplished by real effort, not by mere desires.” — Pañcatantra</p></div></div>
      <div className="flex items-center gap-4"><div className="min-w-24 rounded-xl border border-white/20 bg-white/15 px-4 py-3 text-center backdrop-blur"><Flame className="mx-auto mb-1" size={19} /><p className="text-lg font-extrabold">{streak} Days</p><p className="text-[10px] text-orange-100">Current Streak</p></div><Link href="/lessons" className="rounded-lg bg-white px-5 py-3 text-sm font-bold text-orange-600 transition hover:bg-orange-50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">Continue learning</Link></div>
    </div>
  </section>;
}

export function Statistics({ stats }: { stats: DashboardStats }) {
  const items = [
    ["ANALYTIC STREAK", `${stats?.streak_days || 0} Days`, "Daily Sanskrit quote read", Flame],
    ["MODULES MASTERED", String(stats?.lessons_completed || 0), "Lessons completed", BookOpen],
    ["WORDS LEARNED", `${stats?.words_learned || 0} Words`, "Vocabulary acquired", Languages],
    ["SCHOLAR DAILY XP", `${stats?.points || 0} XP`, "Learning merit earned", Activity],
  ] as const;
  return <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{items.map(([label, value, detail, Icon], index) => <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} key={label} className={`${card} p-4 sm:p-5`}><div className="flex items-center justify-between"><p className="text-[10px] font-bold text-stone-500">{label}</p><Icon size={19} className="text-orange-600" /></div><p className="mt-3 text-xl font-extrabold tracking-tight sm:text-2xl">{value}</p><p className="mt-1 text-xs text-stone-500 dark:text-[var(--text-dim)]">{detail}</p></motion.div>)}</section>;
}

export function CurriculumCard({ lessons }: { lessons: number }) {
  const percent = Math.min(100, Math.round((lessons / 20) * 100));
  return <section className={`${card} p-5 sm:p-6`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">Current curriculum</p><h2 className="mt-1 text-base font-bold">Chapter 8: Sandhi Rules &amp; Phonetics</h2></div><span className="rounded-md bg-orange-50 px-2.5 py-1 text-xs font-bold text-orange-600">{percent}% Complete</span></div><p className="mt-4 max-w-2xl text-sm leading-relaxed text-stone-500 dark:text-[var(--text-dim)]">Learn how vowel sounds merge dynamically at word boundaries. Essential for mastering authentic chanting and recitation syntax.</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-stone-200 dark:bg-white/10"><div className="h-full rounded-full bg-orange-600" style={{ width: `${percent}%` }} /></div><div className="mt-2 flex justify-between text-xs text-stone-500"><span>{lessons} of 20 modules completed</span><span className="hidden font-medium text-stone-700 sm:block dark:text-[var(--text-main)]">Next: Guṇa Sandhi Exercises</span></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-stone-100 pt-4 text-xs text-stone-500 dark:border-white/10"><span>Estimated study time remaining: 25 mins</span><Link href="/lessons" className="rounded-lg bg-stone-900 px-4 py-2.5 font-bold text-white transition hover:bg-orange-600">Resume module</Link></div></section>;
}

export function ChallengeCard() { return <section className={`${card} p-5 sm:p-6`}><div className="flex justify-between gap-3"><p className="eyebrow">Daily analytical challenge</p><span className="rounded bg-orange-50 px-2 py-1 text-[10px] font-bold text-orange-600">+15 XP</span></div><h2 className="mt-3 text-sm font-bold">Translate this grammatical compound:</h2><div className="font-devanagari mt-2 rounded-lg border border-stone-200 bg-[#fdfbf7] px-4 py-3 text-center text-lg font-bold">परमेश्वर</div><p className="mt-2 text-xs italic text-stone-500">Identify the sandhi split and translate both components correctly.</p><div className="mt-4 space-y-2"><button className="w-full rounded-lg border border-stone-200 px-3 py-2.5 text-left text-xs font-medium transition hover:border-orange-300 hover:bg-orange-50 focus-visible:outline-orange-600">A. parama + īśvara (Highest Lord)</button><button className="w-full rounded-lg border border-stone-200 px-3 py-2.5 text-left text-xs font-medium transition hover:border-orange-300 hover:bg-orange-50 focus-visible:outline-orange-600">B. para + meśvara (Beyond the ruler)</button></div></section>; }

export function RecommendedSteps() { return <section className={`${card} p-5 sm:p-6`}><p className="eyebrow">Recommended next steps</p><h2 className="mt-1 text-base font-bold">Intro to Declensions (Vibhaktivāda)</h2><p className="mt-3 text-sm text-stone-500 dark:text-[var(--text-dim)]">A deep structural dive into the 8 noun cases of Sanskrit grammar. Understand how case endings dictate sentence roles without rigid word constraints.</p><div className="mt-4 flex gap-5 text-xs text-stone-500"><span className="flex items-center gap-1.5"><Clock3 size={14} />45 mins</span><span className="flex items-center gap-1.5"><Library size={14} />Grammar Foundation</span></div></section>; }

export function GrammarInstruments() { const tools = [["Compound Deconstructor", "Sandhi Analyst", Languages], ["Morphological parser", "Noun declension", BrainCircuit], ["Sanskrit Dictionary", "Root Lookup", Search]] as const; return <section className={`${card} p-5 sm:p-6`}><h2 className="text-base font-bold">AI Grammar Instruments</h2><div className="mt-4 space-y-2">{tools.map(([title, detail, Icon]) => <Link href={title === "Sanskrit Dictionary" ? "/translation" : "/grammar"} key={title} className="flex items-center gap-3 rounded-lg border border-stone-200 px-3 py-3 transition hover:border-orange-300 hover:bg-orange-50 dark:border-white/10"><span className="grid size-8 place-items-center rounded-md bg-orange-50 text-orange-600"><Icon size={16} /></span><span className="min-w-0 flex-1 text-xs font-bold"><span className="block">{title}</span><span className="font-medium text-stone-500">{detail}</span></span><ChevronRight size={17} className="text-stone-400" /></Link>)}</div></section>; }

export function ActivityFeed({ activities }: { activities: DashboardActivity[] }) { return <section className={`${card} p-5 sm:p-6`}><h2 className="text-base font-bold">Recent Analytical Activity</h2><div className="mt-4 divide-y divide-stone-200 dark:divide-white/10">{activities.length ? activities.map((activity, i) => <div key={`${activity.action}-${i}`} className="flex gap-3 py-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-orange-50 text-orange-600"><Sparkles size={15} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{activity.action}</p><p className="truncate text-xs text-stone-500">{activity.details || "Learning activity"}</p></div><div className="shrink-0 text-right text-xs text-stone-500"><p className="font-bold text-stone-700 dark:text-[var(--text-main)]">{activity.score}</p><p>{activity.timestamp}</p></div></div>) : <p className="py-6 text-sm text-stone-500">Your recent learning activity will appear here.</p>}</div></section>; }

export function Leaderboard({ user, points }: { user: any; points: number }) { return <section className={`${card} p-5 sm:p-6`}><div className="flex items-center justify-between"><h2 className="text-base font-bold">Scholar Leaderboard</h2><span className="text-xs text-stone-500">Your standing</span></div><div className="mt-4 flex items-center gap-3 rounded-lg border border-orange-100 bg-orange-50/70 px-3 py-3"><span className="text-sm font-extrabold text-orange-600">—</span><span className="grid size-8 place-items-center rounded-full bg-stone-800 text-xs font-bold text-white">{String(user?.username || "S").slice(0, 1).toUpperCase()}</span><span className="min-w-0 flex-1 truncate text-sm font-bold">{user?.username}</span><span className="text-xs font-extrabold">{points} XP</span></div><p className="mt-3 text-xs text-stone-500">Complete challenges to improve your cohort ranking.</p></section>; }
